# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.FileField(upload_to='uploads/events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_number', models.IntegerField()),
                ('ship_street', models.CharField(max_length=100)),
                ('ship_unit', models.CharField(max_length=100)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_state', models.CharField(max_length=10)),
                ('ship_zip', models.IntegerField()),
                ('event', models.ManyToManyField(related_name='event_order', to='be_everywhere_app.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='uploads/products')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('permission', models.IntegerField()),
                ('admin_request', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(related_name='product_order', to='be_everywhere_app.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='be_everywhere_app.Users'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to='be_everywhere_app.Users'),
        ),
    ]
